### ISSUE TITLE
command is wrong

### ISSUE THREAD

**Issue by ButcherV** [ccnokes/automate-daily-development-tasks-with-bash#1]
https://github.com/ccnokes/automate-daily-development-tasks-with-bash#view-filefolder-in-default-application-associated-with-it

`open -a TextEdit <file name>` -> `open  <file name> -a TextEdit`

**Comment by ccnokes** [comment]
@ButcherV both forms work for me. What macOS version are you on? Just thinking that maybe something changed with Catalina (which I'm not on yet).

**Comment by ButcherV** [comment]
Version: High Sierra - 10.13.6

**Comment by ccnokes** [comment]
Decided to just change to the syntax you proposed because that seems to work for more OS versions. Thanks!
